version: 1.0.1
info:
  model: int-scaffold
packages:
- name: FLOW_Git_SK_3Project
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: release/1.0.1
services:
- serviceName: project.flow_git_sk_3.integrations:DAF1
  packages:
  - name: FLOW_Git_SK_3Project
    version: 1.0.1
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1069
- serviceName: project.flow_git_sk_3.integrations:DAF2
  packages:
  - name: FLOW_Git_SK_3Project
    version: 1.0.1
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 12.1.0.0.1069
- serviceName: project.flow_git_sk_3.integrations:release
  packages:
  - name: FLOW_Git_SK_3Project
    version: 1.0.1
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: "false"
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
